# Generated by Django 2.2.20 on 2021-04-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=40)),
                ('size_diameter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('regular', 'Regular'), ('square', 'Square')], default='regular', max_length=20)),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', related_query_name='size', to='pizza.Size')),
                ('pizza_topping', models.ManyToManyField(related_name='pizzas', to='pizza.Topping')),
            ],
        ),
    ]
